version: '3.7'
services:
  eye-logs-service:
    container_name: eye_logs
    #    restart: always
    image: eye_logs_image
    build: .
    ports:
      - 8082:8082
    environment:
      ES_HOST: elasticsearch
      SERVICE_PORT: 8082
      EYE_REG_HOST: eye_registry
    network_mode: "eye-network"

networks:
  default:
    external:
      name: eye-network